export const Genre = Object.freeze({
	'Action and Adventure': 1,
	Anthology: 1,
	Art: 1,
	Autobiographies: 1,
	Biographies: 1,
	"Children's": 1,
	Comics: 1,
	Cookbooks: 1,
	Diaries: 1,
	Dictionaries: 1,
	Drama: 1,
	Encyclopedias: 1,
	Fantasy: 1,
	Guide: 1,
	Health: 1,
	History: 1,
	Horror: 1,
	Journals: 1,
	Math: 1,
	Mystery: 1,
	Poetry: 1,
	'Prayer books': 1,
	'Religion, Spirituality & New Age': 1,
	Romance: 1,
	Satire: 1,
	Science: 1,
	'Science Fiction': 1,
	'Self-help': 1,
	Series: 1,
	Travel: 1,
	Trilogy: 1
});
